baseURL = "https://lustrous-figolla-277b02.netlify.app"
languageCode = "en-us"
title = "osinted.dev"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"

    [Params.Tree]
    use = true
    files = [
        ["Github", "https://github.com/Osinted"],
        ["YouTube", "https://www.youtube.com/channel/UC-_K-0EFqSy-NaSxqRp0-SA"],
        ["Discord", "https://discord.dog/osint"]
    ]
